service: notes-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  iam:
    role: ${env:AWS_LAMBDA_ROLE_ARN}
  environment:
    NOTES_TABLE: ${env:NOTES_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}
  build:
    esbuild: false

package:
  individually: true
  exclude:
    - node_modules/aws-sdk/**         # AWS SDK finns redan i Lambda-miljön
    - node_modules/typescript/**      # TypeScript behövs inte under runtime
    - node_modules/@types/**          # Typdefinitioner behövs inte
    - src/**/*.ts                     # TypeScript-filerna behövs inte under runtime
    - .vscode/**                      # Redigerarinställningar
    - .env                            # Miljövariabler ska inte inkluderas direkt
    - tsconfig.json                   # TypeScript-konfigurationsfil behövs inte
    - package-lock.json               # Denna behövs inte under runtime

functions:
  getNotes:
    handler: dist/handlers/index.handler
    events:
      - http:
          path: api/notes
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin