service: notes-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  iam:
    role: ${env:AWS_LAMBDA_ROLE_ARN}
  environment:
    NOTES_TABLE: ${env:NOTES_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  individually: true

functions:
  getNotes:
    handler: dist/handlers/index.handler
    events:
      - http:
          path: api/notes
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin